# Generated by Django 5.2.18 on 2026-10-07 04:27

import catalogo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("clave", models.CharField(editable=False, max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "carrera",
                "verbose_name_plural": "carreras",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Interes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("clave", models.CharField(editable=False, max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "interés",
                "verbose_name_plural": "intereses",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Oportunidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador estable, p. ej. BEC-2026-014. Es la llave de la importación.",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9-]+$",
                                "Solo letras, números y guiones (sin espacios).",
                            )
                        ],
                        verbose_name="código",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="título")),
                (
                    "organizacion",
                    models.CharField(max_length=120, verbose_name="organización"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("beca", "Beca"),
                            ("practicas", "Prácticas y empleo"),
                            ("intercambio", "Intercambio"),
                            ("doble_grado", "Doble grado"),
                            ("concurso", "Concurso"),
                            ("taller", "Taller"),
                            ("voluntariado", "Voluntariado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "todas_carreras",
                    models.BooleanField(
                        default=False, verbose_name="todas las carreras"
                    ),
                ),
                (
                    "ciclo_min",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="ciclo mínimo",
                    ),
                ),
                (
                    "ciclo_max",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="ciclo máximo",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de apertura"
                    ),
                ),
                ("fecha_cierre", models.DateField(verbose_name="fecha de cierre")),
                (
                    "hora_cierre",
                    models.TimeField(
                        blank=True,
                        help_text="Vacía = 23:59 de Lima.",
                        null=True,
                        verbose_name="hora de cierre",
                    ),
                ),
                (
                    "resumen_1",
                    models.CharField(max_length=120, verbose_name="resumen 1"),
                ),
                (
                    "resumen_2",
                    models.CharField(max_length=120, verbose_name="resumen 2"),
                ),
                (
                    "resumen_3",
                    models.CharField(max_length=120, verbose_name="resumen 3"),
                ),
                ("requisitos", models.TextField()),
                (
                    "link_postulacion",
                    models.URLField(
                        max_length=500,
                        validators=[catalogo.models.validar_https],
                        verbose_name="link de postulación",
                    ),
                ),
                (
                    "fuente_url",
                    models.URLField(
                        max_length=500,
                        validators=[catalogo.models.validar_https],
                        verbose_name="fuente",
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("unica", "Única"),
                            ("anual", "Anual"),
                            ("recurrente", "Recurrente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "verificado_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verificada el"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("creado_at", models.DateTimeField(auto_now_add=True)),
                ("actualizado_at", models.DateTimeField(auto_now=True)),
                (
                    "carreras",
                    models.ManyToManyField(
                        blank=True, related_name="oportunidades", to="catalogo.carrera"
                    ),
                ),
                (
                    "intereses",
                    models.ManyToManyField(
                        blank=True, related_name="oportunidades", to="catalogo.interes"
                    ),
                ),
            ],
            options={
                "verbose_name": "oportunidad",
                "verbose_name_plural": "oportunidades",
                "ordering": ["fecha_cierre", "codigo"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ciclo_min__lte", models.F("ciclo_max"))),
                        name="ciclo_min_lte_ciclo_max",
                    )
                ],
            },
        ),
    ]
